#!/usr/bin/env groovy

pipeline {
    agent any

    stages {
        stage('Initialise') {
            steps {
		echo "Initialising job - cloning repo"
                sh 'git clone https://github.com/kseve1/fleetmaninfra.git'
            }
        }
        stage('Test') {
            steps {
		echo "Validating PACKER json..."
                echo 'packer validate packer/jenkins-ec2/packer_jenkins_ami.json'
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploying AMI to AWS...'
                sh 'packer build packer/jenkins-ec2/packer_jenkins_ami.json' 
            }
        }
    }
}
